ESX = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterUsableItem('bread', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('bread', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('bag_bread', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	if xPlayer.canCarryItem('bread', 6) then
        xPlayer.removeInventoryItem('bag_bread', 1)
        xPlayer.addInventoryItem('bread', 6)
    else
        TriggerClientEvent('esx:showNotification', playerId, '你的背包空间已经不够获取更多的物品')
    end
end)

ESX.RegisterUsableItem('snickers', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('snickers', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chocolate', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chocolate', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 50000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('jelly_beans', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('jelly_beans', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 50000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chips', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chips', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('corn_chips', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('corn_chips', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 50000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('nuts', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('nuts', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 50000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('french_fries', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('french_fries', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 50000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('hot_dogs', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('hot_dogs', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('sandwich', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('sandwich', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)
--
--狗粮？
--
ESX.RegisterUsableItem('dogfood', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('dogfood', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 0)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('bagdogfoor', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	if xPlayer.canCarryItem('dogfood', 10) then
        xPlayer.removeInventoryItem('bagdogfoor', 1)
        xPlayer.addInventoryItem('dogfood', 10)
    else
        TriggerClientEvent('esx:showNotification', playerId, '你的背包空间已经不够获取更多的物品')
    end
end)

ESX.RegisterUsableItem('pistachio', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('pistachio', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 80000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('water', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('water', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('bag_water', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	if xPlayer.canCarryItem('water', 24)then
        xPlayer.removeInventoryItem('bag_water', 1)
        xPlayer.addInventoryItem('water', 24)
    else
        TriggerClientEvent('esx:showNotification', playerId, '你的背包空间已经不够获取更多的物品')
    end
end)

ESX.RegisterUsableItem('coke', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('coke', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 50000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('fanta', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('fanta', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 50000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('red_bull', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('red_bull', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('beer2', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	if xPlayer.canCarryItem('beer', 6)then
        xPlayer.removeInventoryItem('beer2', 1)
        xPlayer.addInventoryItem('beer', 6)
    else
        TriggerClientEvent('esx:showNotification', playerId, '你的背包空间已经不够获取更多的物品')
    end
end)

ESX.RegisterUsableItem('beer', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('beer', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
    TriggerClientEvent('esx_status:add', playerId, 'drunk', 100000)--眩晕效果
    TriggerClientEvent('esx_optionalneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('wine', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('wine', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
    TriggerClientEvent('esx_status:add', playerId, 'drunk', 300000)--眩晕效果
    TriggerClientEvent('esx_optionalneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('soda', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('soda', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 50000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('coffee', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('coffee', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('milktea', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('milktea', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('milk', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('milk', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('yogurt', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('yogurt', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 40000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('whisky', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('whisky', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 120000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
    TriggerClientEvent('esx_status:add', playerId, 'drunk', 600000)--眩晕效果
    TriggerClientEvent('esx_optionalneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('vodka', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('vodka', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
    TriggerClientEvent('esx_status:add', playerId, 'drunk', 500000)--眩晕效果
    TriggerClientEvent('esx_optionalneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('tequila', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('tequila', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
    TriggerClientEvent('esx_status:add', playerId, 'drunk', 500000)--眩晕效果
    TriggerClientEvent('esx_optionalneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('rum', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('rum', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
    TriggerClientEvent('esx_status:add', playerId, 'drunk', 400000)--眩晕效果
    TriggerClientEvent('esx_optionalneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('beefyfritosburrito', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('beefyfritosburrito', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('beefyminiquesadilla', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('beefyminiquesadilla', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('appleempanada', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('appleempanada', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('cheesybean_ riceburrito', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('cheesybean_ riceburrito', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('cheeserollup', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('cheeserollup', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('cinnamontwists', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('cinnamontwists', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chickenminiquesadilla', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chickenminiquesadilla', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('spicypotatosofttaco', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('spicypotatosofttaco', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('spicytostada', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('spicytostada', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('triplelayernachos', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('triplelayernachos', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('drpeppervanilla', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('drpeppervanilla', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('mtn_dew', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('mtn_dew', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('starburststrawberry', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('starburststrawberry', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('starburstcherry', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('starburstcherry', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('firecrackerchickenbreast', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('firecrackerchickenbreast', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('orangechicken', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('orangechicken', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('honeysesamechickenbreast', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('honeysesamechickenbreast', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('firecrackershrimp', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('firecrackershrimp', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('honeywalnutshrimp', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('honeywalnutshrimp', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('fiveflavorshrimp', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('fiveflavorshrimp', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chopsuey', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chopsuey', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('sichuanhotchicken', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('sichuanhotchicken', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('generaltso’schicken', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('generaltso’schicken', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('sweetfirechickenbreast', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('sweetfirechickenbreast', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('shanghaiangussteak', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('shanghaiangussteak', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('kungpaochicken', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('kungpaochicken', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('grilledteriyakichicken', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('grilledteriyakichicken', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('broccolibeef', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('broccolibeef', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('beijingbeef', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('beijingbeef', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('veggiespringroll', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('veggiespringroll', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('eggplanttofu', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('eggplanttofu', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chomein', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chomein', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 200000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('fortunecookies', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('fortunecookies', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 50000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('orangejuicea', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('orangejuice', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('applejuice', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('applejuice', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('water', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('water', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('softdrink', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('softdrink', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 50000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('coke', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('coke', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 50000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('bigmac', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('bigmac', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 300000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('cheeseburgers', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('cheeseburgers', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('bacon_clubhouse_burger', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('bacon_clubhouse_burger', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 300000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('crispy_chicken_deluxe', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('crispy_chicken_deluxe', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 300000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('premium_mcwrap', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('premium_mcwrap', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('filet_o_fish', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('filet_o_fish', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chickennugget', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chickennugget', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 300000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('largefries', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('largefries', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 200000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('egg_mcmuffin', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('egg_mcmuffin', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 200000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('sundae', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('sundae', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('pies', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('pies', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('oreo_mcflurry', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('oreo_mcflurry', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('softdrink', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('softdrink', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 50000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('mccafe_shakes', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('mccafe_shakes', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('orange_juice', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('orange_juice', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('hotchocolate', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('hotchocolate', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('icedmocha', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('icedmocha', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('smoothies', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('smoothies', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('whopper', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('whopper', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 600000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('texasdoublewhopper', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('texasdoublewhopper', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 800000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('impossiblewhopper', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('impossiblewhopper', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 650000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('baconking', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('baconking', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 800000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('whopper_jr.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('whopper_jr.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 350000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('baconcheeseburger.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('baconcheeseburger.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 250000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('originalchickensandwich.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('originalchickensandwich.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 300000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('valuefries.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('valuefries.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 200000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('onionrings.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('onionrings.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 200000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chicken_nuggets.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chicken_nuggets.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('chickenclubsalad.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('chickenclubsalad.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 100000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('sundaepie.', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('sundaepie.', 1)
    TriggerClientEvent('esx_status:add', playerId, 'hunger', 150000)
    TriggerClientEvent('esx_basicneeds:onEat', playerId)
end)

ESX.RegisterUsableItem('bkshakes', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('bkshakes', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 150000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('orangejuice', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('orangejuice', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('applejuice', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('applejuice', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterUsableItem('water', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
	xPlayer.removeInventoryItem('water', 1)
    TriggerClientEvent('esx_status:add', playerId, 'thirst', 100000)
    TriggerClientEvent('esx_basicneeds:onDrink', playerId)
end)

ESX.RegisterCommand('heal', 'admin', function(xPlayer, args, showError)
	args.playerId.triggerEvent('esx_basicneeds:healPlayer')
	args.playerId.triggerEvent('chat:addMessage', {args = {'^5HEAL', 'You have been healed.'}})
end, true, {help = 'Heal a player, or yourself - restores thirst, hunger and health.', validate = true, arguments = {
	{name = 'playerId', help = 'the player id', type = 'player'}
}})
