-----COPYRIGHT/OWNER INFO-----
-- Author: Theebu#9267
-- Copyright- This work is protected by:
-- "http://creativecommons.org/licenses/by-nc-nd/4.0/"
-- Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License
-- You must:    Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made.
--                            You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
--              NonCommercial — You may not use the material for commercial purposes. IE you may not sell this
--
-- You may:     Remix, transform, or build upon the material, however you may not distribute that material
--
-- TL;DR: Use this as you will, just don't share it.
-- I only ask you follow this as this is a labor of love. If you wish to share this work with others,
-- send them to: 

Config = {}

Config.MarkerType    			  = 25
Config.MarkerColor                = { r = 0, g = 255, b = 100 }
Config.CarMarkerSize   			  = { x = 2.0, y = 2.0, z = 1.0 }
Config.BikeMarkerSize   		  = { x = 1.0, y = 1.0, z = 1.0 }


Config.bikes        = {8,13}
Config.cars         = {0,1,2,3,4,5,6,7,9,11,12,17,18}
Config.large        = {10,11,19,20}
Config.boats        = {14}

Config.ShowMarkers  = true
Config.UseESX       = true

AddTextEntry('VEH_E_DETATCH', 'Press ~INPUT_CONTEXT~ to detach the vehicle')        -- Text for external detach point
AddTextEntry('VEH_I_AORD', 'Press ~INPUT_CONTEXT~ to attach/detach the vehicle')   -- Text for in boat attach/detach
AddTextEntry('VEH_I_RAMP', 'Press ~INPUT_CONTEXT~ to toggle the ramp')   -- Text for in boat attach/detach

Config.Trailers = {
    {  --cotrailer
        model = 'cotrailer',
        Special = false,
        hasRamp = false,
        unloadPos = {vector3(-2.0,2.0,-0.55)},
        rampPos = {},
        rampText = '',
        isRampExtra = false,
        rampDoorNum = -1,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3(0.0, -1.0, 0.1)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.6, 1.0, 0.1), vector3(-0.6, 1.0, 0.1), vector3(0.6, -1.5, 0.1), vector3(-0.6, -1.5, 0.1)},
        bikeHeightOffset = 0.0,
        attachText = 'Press ~INPUT_CONTEXT~ to attach / release vehicle.',

    },
    {  --thauler
        model = 'thauler',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.5,1.5,-0.25)},
        rampPos = {vector3(1.5, -3.0, -0.25), vector3(-1.5, -3.0, -0.25)},
        rampText = 'Press ~INPUT_CONTEXT~ to fold / unfold ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3(0.0, 0.0, 0.4)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.6, 1.0, 0.4), vector3(-0.6, 1.0, 0.4), vector3(0.6, -1.5, 0.4), vector3(-0.6, -1.5, 0.4)},
        bikeHeightOffset = 0.0,

    },
    {  --btrailer
        model = 'btrailer',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.5,1.5,-0.45)},
        rampPos = {vector3(1.5, -3.0, -0.45), vector3(-1.5, -3.0, -0.45)},
        rampText = 'Press ~INPUT_CONTEXT~ to fold / unfold ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3(0.0, 0.2, 0.1)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.6, 1.0, 0.1), vector3(-0.6, 1.0, 0.1), vector3(0.6, -1.5, 0.1), vector3(-0.6, -1.5, 0.1)},
        bikeHeightOffset = 0.0,

    },
    {  --camperman
        model = 'camperman',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(0.3,-6.5,0.8)},
        rampPos = {vector3(2.0, -6.0, 0.1), vector3(-1.5, -6.0, 0.1)},
        rampText = 'Press ~INPUT_CONTEXT~ to fold / unfold ramp.',
        isRampExtra = false,
        rampDoorNum = 4,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3(0.25, -3.5, 1.0)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(1.0, -2.0, 0.95), vector3(-0.5, -2.0, 0.95), vector3(1.0, -5.0, 0.825), vector3(-0.5, -5.0, 0.825)},
        bikeHeightOffset = 0.0,

    },
    {  --chauler
        model = 'chauler',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.5, 2.5, -0.25)},
        rampPos = {vector3(1.5, -2.7, -0.25), vector3(-1.5, -2.7, -0.25)},
        rampText = 'Press ~INPUT_CONTEXT~ to tilt ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = true,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3(0.0, -0.8, 0.3)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.5, 0.0, 0.3), vector3(-0.5, 0.0, 0.3), vector3(0.7, -2.2, 0.3), vector3(-0.7, -2.2, 0.3)},
        bikeHeightOffset = 0.0,
    },
    {  --cartrailer
        model = 'cartrailer',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-2.0,1.0, -0.75)},
        rampPos = {vector3(1.5, -3.7, -1.0), vector3(-1.5, -3.7, -1.0)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = true,
        rampDoorNum = 5,
        doorwithRamp = false,
        rampextraNum = 1,
        doorwithRampNums = {},
        closeTrunk = true,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3(0.0, -2.0, -0.4)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.5, -1.0, -0.4), vector3(-0.5, -1.0, -0.4), vector3(0.5, -3.5, -0.4), vector3(-0.5, -3.5, -0.4)},
        bikeHeightOffset = 0.0,
    },
    {  --semihauler
        model = 'semihauler',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.8,0.0,-1.4)},
        rampPos = {vector3(-1.8, -7.5, -1.4), vector3(1.8, -7.5, -1.4)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 5.0, 0.0), vector3( 0.0, 0.0, 0.0), vector3( 0.0, -4.5, 0.1)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 3.5, 0.0), vector3(0.8, 1.0, 0.0),
            vector3(0.8, -1.5, 0.0), vector3(0.8, -4.0, 0.0),
            vector3(-0.8, 3.5, 0.0), vector3(-0.8, 1.0, 0.0),
            vector3(-0.8, -1.5, 0.0), vector3(-0.8, -4.0, 0.0)},
        bikeHeightOffset = 0.0,
    },
    {  --bigtex40
        model = 'bigtex40',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.8,5.0,-0.8)},
        rampPos = {vector3(-1.8, -5.0, -0.8), vector3(1.8, -5.0, -0.8)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 3.0, -0.15), vector3( 0.0, -3.0, -0.15), vector3( 0.0, 0.5, -0.15)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 3.5, -0.15), vector3(0.8, 1.0,-0.15),vector3(0.8, -1.5, -0.15),vector3(0.8, -4.0, -0.15),
                        vector3(-0.8, 3.5, -0.15),vector3(-0.8, 1.0, -0.15),vector3(-0.8, -1.5, -0.15),vector3(-0.8, -4.0, -0.15)},
        bikeHeightOffset = 0.0,
    },
    {  --bigtex20
        model = 'bigtex20',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.8,3.0,-0.8)},
        rampPos = {vector3(-1.8, -3.0, -0.8), vector3(1.8, -3.0, -0.8)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 1.0, -0.15)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 3.5, -0.15), vector3(0.8, 1.0, -0.15),vector3(0.8, -1.5, -0.15),
                        vector3(-0.8, 3.5, -0.15),vector3(-0.8, 1.0,-0.15),vector3(-0.8, -1.5, -0.15)},
        bikeHeightOffset = 0.0,
    },
    {  --godzhauler
        model = 'godzhauler',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(-1.8, 1.0,0.1)},
        rampPos = {vector3(-1.8, -5.0, 0.1), vector3(1.8, -5.0, 0.1)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 4.5, 1.0), vector3( 0.0, 1.0, 1.0), vector3( 0.0, -3.0, 1.0)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 3.5, 1.0), vector3(0.8, 1.0, 1.0),vector3(0.8, -1.5, 1.0),vector3(0.8, -4.0, 1.0),vector3(0.8, 6.0, 1.0),
                        vector3(-0.8, 3.5, 1.0),vector3(-0.8, 1.0, 1.0),vector3(-0.8, -1.5, 1.0),vector3(-0.8, -4.0, 1.0),vector3(-0.8, 6.0, 1.0)},
        bikeHeightOffset = 0.0,
    },
    {  --godzenclosed
        model = 'godzenclosed',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(0.0, -6.0, -0.5)},
        rampPos = {vector3(-1.8, -5.5, -0.5), vector3(1.8, -5.5, -0.5)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = -1,
        doorwithRamp = true,
        rampextraNum = 3,
        doorwithRampNums = {2,3},
        closeTrunk = false,
        hasDoors = true,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 2.5, -0.5), vector3( 0.0, 0.5, -0.5), vector3( 0.0, -3.5, -0.5)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 2.5, -0.5), vector3(0.8, 0.0, -0.5),vector3(0.8, -2.5, -0.5),vector3(0.8, -5.0, -0.5),
                        vector3(-0.8, 2.5, -0.5),vector3(-0.8, 0.0, -0.5),vector3(-0.8, -2.5, -0.5),vector3(-0.8, -5.0, -0.5)},
        bikeHeightOffset = 0.0,
    },
    {  --enclosedgoose
        model = 'enclosedgoose',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(0.0, -6.0, 0.0)},
        rampPos = {vector3(-1.8, -5.5, -0.5), vector3(1.8, -5.5, -0.5)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        rampextraNum = -1,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 2.5, 0.0), vector3( 0.0, -0.5, 0.0), vector3( 0.0, -3.5, 0.0)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 2.5, -0.5), vector3(0.8, 0.0, -0.5),vector3(0.8, -2.5, -0.5),vector3(0.8, -5.0, -0.5),
                        vector3(-0.8, 2.5, -0.5),vector3(-0.8, 0.0, -0.5),vector3(-0.8, -2.5, -0.5),vector3(-0.8, -5.0, -0.5)},
        bikeHeightOffset = 0.0,
    },
    {  --trailers3
        model = 'trailers3',
        Special = false,
        hasRamp = true,
        unloadPos = {vector3(0.0, -5.5, -1.50)},
        rampPos = {vector3(-1.8, -5.5, -3.0), vector3(1.8, -5.5, -3.0)},
        rampText = 'Press ~INPUT_CONTEXT~ to extend / retract ramp.',
        isRampExtra = false,
        rampDoorNum = 5,
        doorwithRamp = false,
        doorwithRampNums = {},
        closeTrunk = false,
        hasDoors = false,
        doorPositions = {},
        doorText = '',
        carPositions = {vector3( 0.0, 2.5, -1.5), vector3( 0.0, -3.5, -1.5)},
        carHeightOffset = 0.0,
        bikePositions = {vector3(0.8, 3.5, 0.0), vector3(0.8, 1.0, 0.0),
            vector3(0.8, -1.5, 0.0), vector3(0.8, -4.0, 0.0),
            vector3(-0.8, 3.5, 0.0), vector3(-0.8, 1.0, 0.0),
            vector3(-0.8, -1.5, 0.0), vector3(-0.8, -4.0, 0.0)},
        bikeHeightOffset = 0.0,
    },
}